from typing import List, Dict, Any, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.database.session import get_db
from app.models.user import User
from app.models.lesson import Lesson, LessonSection, Question
from app.routers.auth import ensure_demo_user
from app.schemas.lesson import LessonResponse

router = APIRouter(prefix="/api/demo", tags=["Hackathon Demo Mode"])

COURSES_CATALOG = [
    {
        "id": "ohms-law",
        "slug": "ohms-law",
        "title": "Ohm's Law & Circuit Dynamics",
        "subject": "Physics",
        "level": "Beginner",
        "duration": "15 Mins",
        "sections_count": 3,
        "description": "Master the fundamental triad: Voltage (V), Current (I), and Resistance (R) with interactive circuit simulation and water pipe analogies.",
        "icon": "Zap",
        "color": "cyan",
        "featured": True,
        "visual_type": "circuit"
    },
    {
        "id": "neural-networks",
        "slug": "neural-networks",
        "title": "Neural Networks & Backpropagation",
        "subject": "Computer Science",
        "level": "Intermediate",
        "duration": "20 Mins",
        "sections_count": 3,
        "description": "Understand weights, biases, ReLU/Sigmoid activation functions, and gradient descent optimization using visual hill-climbing analogies.",
        "icon": "Cpu",
        "color": "purple",
        "featured": True,
        "visual_type": "neural_net"
    },
    {
        "id": "calculus-derivatives",
        "slug": "calculus-derivatives",
        "title": "Calculus: Derivatives as Rates of Change",
        "subject": "Mathematics",
        "level": "Beginner to Intermediate",
        "duration": "15 Mins",
        "sections_count": 3,
        "description": "Understand instantaneous rate of change, tangent slopes, and the power rule with interactive curve secants and speedometer analogies.",
        "icon": "Activity",
        "color": "emerald",
        "featured": True,
        "visual_type": "calculus"
    },
    {
        "id": "chemical-bonding",
        "slug": "chemical-bonding",
        "title": "Chemical Bonding & Reaction Kinetics",
        "subject": "Chemistry",
        "level": "Intermediate",
        "duration": "18 Mins",
        "sections_count": 3,
        "description": "Discover collision theory, activation energy barriers, and how catalysts speed up reactions by lowering the energetic mountain.",
        "icon": "FlaskConical",
        "color": "amber",
        "featured": True,
        "visual_type": "chemistry"
    },
    {
        "id": "dna-genetics",
        "slug": "dna-genetics",
        "title": "DNA Structure, Replication & Central Dogma",
        "subject": "Biology",
        "level": "Beginner",
        "duration": "16 Mins",
        "sections_count": 3,
        "description": "Explore the double helix architecture, complementary base pairing (A-T, G-C), and semi-conservative replication machinery.",
        "icon": "Dna",
        "color": "rose",
        "featured": True,
        "visual_type": "biology"
    }
]

def seed_ohms_law(db: Session, user_id: int) -> Lesson:
    existing = db.query(Lesson).filter(Lesson.user_id == user_id, Lesson.title.like("%Ohm%")).first()
    if existing:
        db.delete(existing)
        db.commit()

    lesson = Lesson(
        user_id=user_id,
        title="Class 10 Physics: Ohm's Law & Circuit Fundamentals",
        subject="Physics",
        learning_objective="Understand the mathematical and physical relationship between Voltage, Current, and Resistance (V = IR).",
        learning_mode="complete_learning",
        target_level="Beginner",
        duration_minutes=15,
        language="English",
        teaching_style="Friendly Mentor",
        total_sections=3,
        current_section_index=0,
        current_mastery=50.0,
        status="in_progress",
        curriculum_summary={
            "total_concepts": 3,
            "completed_concepts_count": 0,
            "estimated_total_minutes": 15,
            "prerequisites_tree": ["Voltage -> Ohm's Law", "Ohm's Law -> Circuit Lab"],
            "continuation_plan": "Systematic mastery of circuit dynamics."
        }
    )
    db.add(lesson)
    db.flush()

    sec1 = LessonSection(
        lesson_id=lesson.id,
        section_index=0,
        title="Understanding Electric Potential (Voltage)",
        concept="Voltage as Electrical Pressure",
        explanation_text="Voltage is the electrical potential difference that drives electric charges through a conductor. Think of it as electrical pressure generated by a battery.",
        example_text="A 1.5V AA battery provides 1.5 Joules of potential per Coulomb of charge.",
        analogy_text="Water stored in a water tower: higher elevation creates higher pressure at the faucet.",
        prerequisites=[],
        importance="essential",
        status="in_progress",
        scenes=[
            {"scene_id": 1, "title": "Intro to Voltage", "type": "talking_head"},
            {"scene_id": 2, "title": "Potential Difference", "type": "explanation"},
            {"scene_id": 3, "title": "Water Tower Analogy", "type": "analogy"},
            {"scene_id": 4, "title": "Voltage Checkpoint", "type": "interactive_quiz"}
        ],
        visual_type="svg_diagram",
        visual_data={"diagram_type": "circuit_flow", "voltage": "12V", "particles": 15},
        visual_caption="Figure 1: Potential Difference driving electrons through a circuit",
        key_points=[
            "Voltage is measured in Volts (V)",
            "It acts as the pushing force in circuits",
            "Without voltage, no net current flows"
        ],
        narration_script="Welcome! Today we are exploring the foundational rule of electricity: Ohm's Law. Let's first picture Voltage as electrical pressure.",
        estimated_minutes=3
    )
    db.add(sec1)
    db.flush()

    q1 = Question(
        lesson_id=lesson.id,
        section_id=sec1.id,
        question_type="mcq",
        question_text="What is the primary role of Voltage in an electric circuit?",
        options=[
            {"id": "A", "text": "It restricts electron flow"},
            {"id": "B", "text": "It provides the electrical push/pressure that drives current"},
            {"id": "C", "text": "It absorbs electromagnetic radiation"},
            {"id": "D", "text": "It destroys charged particles"}
        ],
        correct_answer="B",
        explanation="Voltage is the potential difference providing the force for electrons to move.",
        difficulty="easy",
        concept_tested="Voltage Definition"
    )
    db.add(q1)

    sec2 = LessonSection(
        lesson_id=lesson.id,
        section_index=1,
        title="Ohm's Law: The Interplay of V, I, and R",
        concept="Inverse Relationship: I = V / R",
        explanation_text="Georg Ohm discovered that electric Current (I) is directly proportional to Voltage (V) and inversely proportional to Resistance (R). When resistance increases at constant voltage, current must decrease!",
        example_text="If V = 12V and R = 4 Ohms, I = 12 / 4 = 3 Amperes.",
        analogy_text="Water pipe constriction: Squeezing a water hose (increasing resistance) with fixed faucet pressure throttles down the amount of water coming out.",
        visual_type="katex",
        visual_data={
            "formula": "V = I \\times R \\iff I = \\frac{V}{R}",
            "variables": [
                {"symbol": "V", "name": "Voltage", "unit": "Volts (V)"},
                {"symbol": "I", "name": "Current", "unit": "Amperes (A)"},
                {"symbol": "R", "name": "Resistance", "unit": "Ohms (\\Omega)"}
            ]
        },
        visual_caption="Ohm's Law Formula & Variable Units",
        key_points=[
            "Current is inversely proportional to resistance: I = V / R",
            "Increasing resistance forces current to DECREASE",
            "Resistance is measured in Ohms (Ω)"
        ],
        narration_script="Now for the signature relationship: Ohm's Law. Current equals Voltage divided by Resistance. When resistance increases, current decreases.",
        estimated_minutes=4
    )
    db.add(sec2)
    db.flush()

    q2 = Question(
        lesson_id=lesson.id,
        section_id=sec2.id,
        question_type="mcq",
        question_text="What happens to current if resistance increases while voltage remains constant?",
        options=[
            {"id": "A", "text": "Current increases"},
            {"id": "B", "text": "Current decreases"},
            {"id": "C", "text": "Current remains unchanged"},
            {"id": "D", "text": "Voltage automatically doubles"}
        ],
        correct_answer="B",
        explanation="Because I = V / R, when resistance R increases, the denominator grows, reducing current I.",
        difficulty="medium",
        concept_tested="Ohm's Law Inverse Relationship"
    )
    db.add(q2)

    sec3 = LessonSection(
        lesson_id=lesson.id,
        section_index=2,
        title="Circuit Calculation & Practical Load",
        concept="Applying I = V / R to Real Appliances",
        explanation_text="Let's apply Ohm's Law to calculate current in an actual appliance circuit.",
        example_text="A 120V circuit powering a 30 Ohm toaster draws I = 120 / 30 = 4 Amperes.",
        analogy_text="Regulating flow through specialized nozzles.",
        visual_type="mermaid",
        visual_data={
            "diagram": "graph LR\n  Battery[12V Source] --> Switch[Closed Switch]\n  Switch --> Resistor[Load R = 3 Ohms]\n  Resistor --> Battery\n  style Resistor fill:#38bdf8,stroke:#0284c7,stroke-width:2px"
        },
        visual_caption="Simple DC Circuit with 3 Ohm Load",
        key_points=[
            "Always align units: Volts, Amperes, Ohms",
            "Current can be calculated by dividing Voltage by Resistance",
            "Circuit safety depends on keeping current within rated limits"
        ],
        narration_script="Now let's compute real current in an active circuit.",
        estimated_minutes=3
    )
    db.add(sec3)
    db.flush()

    q3 = Question(
        lesson_id=lesson.id,
        section_id=sec3.id,
        question_type="short_answer",
        question_text="A circuit has a 24V supply and a 6 Ohm resistor. Calculate the current in Amperes.",
        options=[],
        correct_answer="4",
        explanation="I = V / R = 24 / 6 = 4 Amperes.",
        difficulty="medium",
        concept_tested="Ohm's Law Calculation"
    )
    db.add(q3)

    db.commit()
    db.refresh(lesson)
    return lesson

def seed_neural_networks(db: Session, user_id: int) -> Lesson:
    existing = db.query(Lesson).filter(Lesson.user_id == user_id, Lesson.title.like("%Neural%")).first()
    if existing:
        db.delete(existing)
        db.commit()

    lesson = Lesson(
        user_id=user_id,
        title="Deep Learning: Neural Networks & Backpropagation",
        subject="Computer Science",
        learning_objective="Master artificial neurons, forward pass summation (z = w*x + b), activation functions (ReLU/Sigmoid), and gradient descent.",
        target_level="Intermediate",
        duration_minutes=20,
        language="English",
        teaching_style="Coding Mentor",
        total_sections=3,
        current_section_index=0,
        current_mastery=40.0,
        status="in_progress"
    )
    db.add(lesson)
    db.flush()

    sec1 = LessonSection(
        lesson_id=lesson.id,
        section_index=0,
        title="The Artificial Perceptron: Inputs, Weights & Bias",
        concept="Weighted Summation: z = Sum(w_i * x_i) + b",
        explanation_text="An artificial neuron takes multiple inputs (x), scales each by its importance weight (w), adds a threshold bias (b), and computes the net stimulus z = w1*x1 + w2*x2 + b.",
        example_text="If x1=2 with weight w1=0.5, and x2=3 with weight w2=-1, with bias b=1: z = (2*0.5) + (3*-1) + 1 = 1 - 3 + 1 = -1.",
        analogy_text="A committee decision where committee members have varying voting power (weights).",
        visual_type="neural_net",
        visual_data={"inputs": [2, 3], "weights": [0.5, -1.0], "bias": 1.0},
        visual_caption="Figure 1: 2-Input Artificial Neuron computing weighted sum",
        key_points=[
            "Inputs represent features; weights represent connection strengths",
            "Positive weights amplify; negative weights suppress signals",
            "Bias shifts the activation threshold independent of inputs"
        ],
        narration_script="Welcome to Deep Learning! Today we uncover how artificial neural networks learn. Let's start with the foundational building block: the single neuron.",
        estimated_minutes=5
    )
    db.add(sec1)
    db.flush()

    q1 = Question(
        lesson_id=lesson.id,
        section_id=sec1.id,
        question_type="mcq",
        question_text="In an artificial neuron, what is the role of the weights (w)?",
        options=[
            {"id": "A", "text": "They permanently delete inputs"},
            {"id": "B", "text": "They determine the relative importance or influence of each input feature"},
            {"id": "C", "text": "They convert numbers into text"},
            {"id": "D", "text": "They guarantee the output is always zero"}
        ],
        correct_answer="B",
        explanation="Weights determine how much influence each corresponding feature has on the neuron's decision.",
        difficulty="easy",
        concept_tested="Neuron Weights"
    )
    db.add(q1)

    sec2 = LessonSection(
        lesson_id=lesson.id,
        section_index=1,
        title="Activation Functions: Introducing Non-Linearity",
        concept="Why Pure Linear Layers Fail: ReLU and Sigmoid",
        explanation_text="Without activation functions, stacking 100 neural layers still equals a single linear equation (w2*(w1*x) = w_net*x). Activation functions like ReLU (max(0, z)) and Sigmoid allow the network to learn non-linear decision boundaries like circles and spirals.",
        example_text="ReLU(-3) = 0, while ReLU(4.5) = 4.5. It passes positive signals while zeroing out negatives.",
        analogy_text="A dimmer switch with a minimum threshold: below the threshold nothing turns on, but above it light scales smoothly.",
        visual_type="katex",
        visual_data={"formula": "\\text{ReLU}(z) = \\max(0, z) \\quad \\text{and} \\quad \\sigma(z) = \\frac{1}{1 + e^{-z}}"},
        visual_caption="Non-Linear Activation Functions",
        key_points=[
            "Without non-linear activations, deep networks collapse into a single linear regression",
            "ReLU (Rectified Linear Unit) is the industry standard for hidden layers",
            "Sigmoid maps any real number to a probability between 0 and 1"
        ],
        narration_script="Now let us introduce the magic of deep learning: non-linear activation functions. Without them, a neural network is just a flat line!",
        estimated_minutes=5
    )
    db.add(sec2)
    db.flush()

    q2 = Question(
        lesson_id=lesson.id,
        section_id=sec2.id,
        question_type="mcq",
        question_text="Why are non-linear activation functions essential in deep neural networks?",
        options=[
            {"id": "A", "text": "To force the network to only solve linear problems"},
            {"id": "B", "text": "To enable the network to learn complex non-linear patterns and avoid collapsing into a single linear transformation"},
            {"id": "C", "text": "To double the physical RAM of the graphics card"},
            {"id": "D", "text": "To prevent code from compiling"}
        ],
        correct_answer="B",
        explanation="Activation functions introduce curvature and non-linearity, allowing deep networks to approximate any mathematical function.",
        difficulty="medium",
        concept_tested="Activation Functions"
    )
    db.add(q2)

    sec3 = LessonSection(
        lesson_id=lesson.id,
        section_index=2,
        title="Training via Loss & Gradient Descent",
        concept="Backpropagation: Finding the Valley of Minimum Error",
        explanation_text="Training means tuning weights to minimize the loss (error) between prediction and ground truth. Gradient descent calculates the partial derivative of loss with respect to each weight (dL/dw) and takes a step in the downhill direction: w_new = w_old - alpha * (dL/dw).",
        example_text="If gradient dL/dw is positive (e.g. +2), increasing w increases error; so we decrease w!",
        analogy_text="A hiker blindfolded in a thick fog finding their way down a mountain valley by feeling which direction slopes downward underfoot.",
        visual_type="mermaid",
        visual_data={"diagram": "graph LR\n  Input --> Forward[Forward Pass: Prediction]\n  Forward --> Loss[Compute Loss Error]\n  Loss --> Backprop[Backpropagation: Gradients dL/dw]\n  Backprop --> Update[Update Weights: w -= lr * grad]\n  Update --> Forward"},
        visual_caption="The Backpropagation Learning Loop",
        key_points=[
            "Loss measures prediction error",
            "Gradients indicate which direction increases error",
            "We subtract the gradient to step downhill towards minimal loss"
        ],
        narration_script="Finally, let's explore how neural networks learn: through backpropagation and gradient descent downhill into the valley of lowest error.",
        estimated_minutes=5
    )
    db.add(sec3)
    db.flush()

    q3 = Question(
        lesson_id=lesson.id,
        section_id=sec3.id,
        question_type="mcq",
        question_text="In gradient descent, what does a positive gradient (dL/dw > 0) tell us to do with the weight w?",
        options=[
            {"id": "A", "text": "Increase the weight w"},
            {"id": "B", "text": "Decrease the weight w to reduce the error"},
            {"id": "C", "text": "Set the weight to infinity"},
            {"id": "D", "text": "Do nothing"}
        ],
        correct_answer="B",
        explanation="Because dL/dw > 0 means increasing w increases error, gradient descent steps in the opposite direction (w = w - lr * grad), decreasing w.",
        difficulty="medium",
        concept_tested="Gradient Descent"
    )
    db.add(q3)

    db.commit()
    db.refresh(lesson)
    return lesson

def seed_calculus(db: Session, user_id: int) -> Lesson:
    existing = db.query(Lesson).filter(Lesson.user_id == user_id, Lesson.title.like("%Calculus%")).first()
    if existing:
        db.delete(existing)
        db.commit()

    lesson = Lesson(
        user_id=user_id,
        title="Calculus: Derivatives as Instantaneous Rates of Change",
        subject="Mathematics",
        learning_objective="Understand limits, tangent lines, secant approximations, and the power rule for calculating derivatives.",
        target_level="Beginner",
        duration_minutes=15,
        language="English",
        teaching_style="Professor",
        total_sections=3,
        current_section_index=0,
        current_mastery=35.0,
        status="in_progress"
    )
    db.add(lesson)
    db.flush()

    sec1 = LessonSection(
        lesson_id=lesson.id,
        section_index=0,
        title="Instantaneous Velocity vs Average Speed",
        concept="The Need for the Derivative",
        explanation_text="Average speed is simple: total distance divided by total elapsed time (Delta s / Delta t). But what if you want your exact speed at the exact instant t = 2.000 seconds? The elapsed time is zero, leading to the forbidden fraction 0/0!",
        example_text="Driving 60 miles in 1 hour means your average speed is 60 mph. But you might have stopped at red lights and cruised at 80 mph in between.",
        analogy_text="A police radar gun that captures your instantaneous speed at a single frozen millisecond, rather than calculating your total commute average.",
        visual_type="speedometer",
        visual_data={"speed": 65, "limit": 60},
        visual_caption="Instantaneous Velocity vs Trip Average",
        key_points=[
            "Average rate of change is measured across a finite time interval",
            "Instantaneous rate of change requires shrinking the time interval to zero",
            "Calculus was invented by Newton and Leibniz precisely to resolve the 0/0 paradox"
        ],
        narration_script="Welcome to Calculus! Today we unlock one of the greatest intellectual breakthroughs in human history: the derivative.",
        estimated_minutes=4
    )
    db.add(sec1)
    db.flush()

    q1 = Question(
        lesson_id=lesson.id,
        section_id=sec1.id,
        question_type="mcq",
        question_text="Why can't instantaneous velocity be calculated using simple division (Distance / Time) without calculus?",
        options=[
            {"id": "A", "text": "Because cars move too fast for math"},
            {"id": "B", "text": "Because at an exact instant in time, elapsed time Delta t is 0, which would require dividing by zero (0/0)"},
            {"id": "C", "text": "Because speedometers do not measure distance"},
            {"id": "D", "text": "Because velocity is always constant in reality"}
        ],
        correct_answer="B",
        explanation="At an exact frozen instant, both distance traveled and elapsed time are zero, creating an undefined 0/0 expression that requires limits to evaluate.",
        difficulty="easy",
        concept_tested="Instantaneous Rate"
    )
    db.add(q1)

    sec2 = LessonSection(
        lesson_id=lesson.id,
        section_index=1,
        title="The Tangent Line Problem & The Limit Definition",
        concept="Secant Line to Tangent Line as Delta x -> 0",
        explanation_text="A secant line passes through two points (x, f(x)) and (x+h, f(x+h)) with slope [f(x+h) - f(x)] / h. As we slide the second point closer (taking the limit as h approaches 0), the secant line morphs seamlessly into the tangent line at x!",
        example_text="For f(x) = x^2: [(x+h)^2 - x^2]/h = [x^2 + 2xh + h^2 - x^2]/h = (2xh + h^2)/h = 2x + h. As h -> 0, this equals 2x!",
        analogy_text="Zooming into a curved highway on satellite view: zoom in close enough to any single point and the curve appears perfectly straight.",
        visual_type="katex",
        visual_data={"formula": "f'(x) = \\lim_{h \\to 0} \\frac{f(x + h) - f(x)}{h}"},
        visual_caption="The Formal Limit Definition of the Derivative",
        key_points=[
            "Secant slope measures average change; tangent slope measures instantaneous change",
            "The derivative f'(x) is the slope of the tangent line at x",
            "Taking the limit as h -> 0 safely cancels out the problematic denominator"
        ],
        narration_script="Now observe how sliding two points together turns a secant line into a tangent line. The slope of that tangent line is your derivative!",
        estimated_minutes=5
    )
    db.add(sec2)
    db.flush()

    q2 = Question(
        lesson_id=lesson.id,
        section_id=sec2.id,
        question_type="mcq",
        question_text="Geometrically, what does the derivative f'(a) represent on the graph of y = f(x)?",
        options=[
            {"id": "A", "text": "The total area under the curve from 0 to a"},
            {"id": "B", "text": "The exact slope of the tangent line to the curve at the point x = a"},
            {"id": "C", "text": "The y-intercept of the function"},
            {"id": "D", "text": "The length of the x-axis"}
        ],
        correct_answer="B",
        explanation="The derivative at any point equals the slope (steepness) of the tangent line touching the curve at that exact point.",
        difficulty="medium",
        concept_tested="Geometric Derivative"
    )
    db.add(q2)

    sec3 = LessonSection(
        lesson_id=lesson.id,
        section_index=2,
        title="The Power Rule & Instantaneous Slope Calculation",
        concept="Shortcut: d/dx [x^n] = n * x^(n-1)",
        explanation_text="Instead of working through the limit definition every time, the Power Rule gives us an immediate shortcut: bring the exponent down to multiply, and decrease the power by 1. d/dx [x^3] = 3x^2.",
        example_text="For f(x) = x^4, f'(x) = 4x^3. At x = 2, the instantaneous slope is 4*(2^3) = 4*8 = 32!",
        analogy_text="A calculation cheat-code: shifting down gears in a car to instantly compute high-speed acceleration.",
        visual_type="katex",
        visual_data={"formula": "\\frac{d}{dx}[x^n] = n x^{n - 1} \\quad \\implies \\quad \\frac{d}{dx}[x^3] = 3x^2"},
        visual_caption="The Power Rule Formula",
        key_points=[
            "Bring the exponent down in front as a multiplier",
            "Subtract 1 from the exponent",
            "Constants have a derivative of zero because they never change"
        ],
        narration_script="Now let's harness the power rule! This shortcut lets you calculate tangent slopes across physics, finance, and engineering in milliseconds.",
        estimated_minutes=4
    )
    db.add(sec3)
    db.flush()

    q3 = Question(
        lesson_id=lesson.id,
        section_id=sec3.id,
        question_type="short_answer",
        question_text="Using the power rule, what is the derivative of f(x) = x^2 evaluated at x = 3?",
        options=[],
        correct_answer="6",
        explanation="The derivative of x^2 is 2x. Evaluated at x = 3, f'(3) = 2 * 3 = 6.",
        difficulty="medium",
        concept_tested="Power Rule Application"
    )
    db.add(q3)

    db.commit()
    db.refresh(lesson)
    return lesson

def seed_chemistry(db: Session, user_id: int) -> Lesson:
    existing = db.query(Lesson).filter(Lesson.user_id == user_id, Lesson.title.like("%Chemistry%")).first()
    if existing:
        db.delete(existing)
        db.commit()

    lesson = Lesson(
        user_id=user_id,
        title="Chemistry: Chemical Bonding & Reaction Kinetics",
        subject="Chemistry",
        learning_objective="Understand ionic vs covalent bonding, collision theory, activation energy barriers, and the catalytic lowering of transition states.",
        target_level="Intermediate",
        duration_minutes=18,
        language="English",
        teaching_style="Patient Tutor",
        total_sections=3,
        current_section_index=0,
        current_mastery=30.0,
        status="in_progress"
    )
    db.add(lesson)
    db.flush()

    sec1 = LessonSection(
        lesson_id=lesson.id,
        section_index=0,
        title="Why Atoms Bond: Valence Shells & The Octet Rule",
        concept="Ionic Transfer vs Covalent Sharing",
        explanation_text="Atoms form bonds to achieve stable electron configurations (usually 8 valence electrons, the octet rule). In ionic bonds, metal atoms surrender electrons to non-metals (like Na+ and Cl-). In covalent bonds, atoms share electron pairs (like H2O).",
        example_text="Sodium (Na) has 1 valence electron and Chlorine (Cl) has 7. Na transfers 1 electron to Cl, creating strong electrostatic attraction (NaCl table salt).",
        analogy_text="Ionic bonding is donating furniture; covalent bonding is two roommates sharing a couch.",
        visual_type="katex",
        visual_data={"formula": "\\text{Na} + \\text{Cl} \\longrightarrow \\text{Na}^+ + \\text{Cl}^- \\longrightarrow \\text{NaCl}"},
        visual_caption="Ionic Electron Transfer Mechanism",
        key_points=[
            "Octet rule: atoms seek 8 valence electrons for noble gas stability",
            "Ionic bonds involve full electron transfer between ions of opposite charge",
            "Covalent bonds involve shared electron pairs between non-metals"
        ],
        narration_script="Welcome to Chemistry! Today we explore why matter holds together and how chemical transformations occur at the molecular level.",
        estimated_minutes=4
    )
    db.add(sec1)
    db.flush()

    q1 = Question(
        lesson_id=lesson.id,
        section_id=sec1.id,
        question_type="mcq",
        question_text="What is the fundamental difference between an ionic bond and a covalent bond?",
        options=[
            {"id": "A", "text": "Ionic bonds are between gases only"},
            {"id": "B", "text": "Ionic bonds involve electron transfer between ions; covalent bonds involve shared electron pairs"},
            {"id": "C", "text": "Covalent bonds destroy electrons"},
            {"id": "D", "text": "There is no difference"}
        ],
        correct_answer="B",
        explanation="Ionic bonds form via electrostatic attraction after electron transfer, whereas covalent bonds form when atoms share electron pairs.",
        difficulty="easy",
        concept_tested="Bond Types"
    )
    db.add(q1)

    sec2 = LessonSection(
        lesson_id=lesson.id,
        section_index=1,
        title="Collision Theory & Activation Energy (Ea)",
        concept="Why Not All Collisions Cause Reactions",
        explanation_text="For molecules to react, they must collide with two mandatory conditions: 1) correct spatial orientation, and 2) sufficient kinetic energy greater than or equal to the Activation Energy barrier (E >= Ea). Without enough speed, molecules simply bounce apart elastically!",
        example_text="Striking a match: a gentle touch does nothing. You must strike it briskly with friction to provide the activation energy needed to ignite the phosphorus head.",
        analogy_text="Rolling a skateboard up a steep skatepark hill: if you don't push hard enough, you roll halfway up and slide right back down without reaching the other side.",
        visual_type="energy_diagram",
        visual_data={"reactants_energy": 20, "activation_barrier": 80, "products_energy": 40},
        visual_caption="Potential Energy Diagram: Reactants overcoming the Activation Barrier (Ea)",
        key_points=[
            "Molecules must collide with sufficient kinetic energy >= Ea",
            "Molecules must have correct geometric orientation",
            "Raising temperature increases the percentage of particles possessing energy >= Ea"
        ],
        narration_script="Now notice why molecules don't just react instantly upon touching: they must conquer the energetic mountain known as Activation Energy.",
        estimated_minutes=5
    )
    db.add(sec2)
    db.flush()

    q2 = Question(
        lesson_id=lesson.id,
        section_id=sec2.id,
        question_type="mcq",
        question_text="According to Collision Theory, why does heating up a reaction mixture accelerate the reaction rate?",
        options=[
            {"id": "A", "text": "It cools down the molecules"},
            {"id": "B", "text": "Particles move faster, increasing collision frequency AND the fraction of collisions with energy >= Ea"},
            {"id": "C", "text": "It turns all atoms into gold"},
            {"id": "D", "text": "It deletes the activation energy completely"}
        ],
        correct_answer="B",
        explanation="Higher temperatures increase molecular kinetic velocity, exponentially multiplying the fraction of molecules capable of surmounting the activation energy barrier.",
        difficulty="medium",
        concept_tested="Collision Theory & Temperature"
    )
    db.add(q2)

    sec3 = LessonSection(
        lesson_id=lesson.id,
        section_index=2,
        title="Catalysts: Lowering the Energetic Mountain",
        concept="Alternative Reaction Pathways Without Being Consumed",
        explanation_text="A catalyst speeds up a chemical reaction by providing an alternative reaction pathway with a significantly lower activation energy (Ea). Because the barrier is lower, far more collisions successfully react at the same temperature. Crucially, the catalyst emerges completely unchanged at the end!",
        example_text="Enzymes in your body: Catalase breaks down toxic hydrogen peroxide into water and oxygen millions of times faster than uncatalyzed degradation.",
        analogy_text="Carving a tunnel through a mountain instead of forcing cars to climb over the snowy summit.",
        visual_type="katex",
        visual_data={"formula": "k = A \\cdot e^{-\\frac{E_a}{R T}} \\quad \\implies \\quad \\text{Lower } E_a \\implies \\text{Higher Rate } k"},
        visual_caption="The Arrhenius Equation: Rate constant k increases exponentially as Ea decreases",
        key_points=[
            "Catalysts lower the activation energy barrier (Ea)",
            "They do not alter the net energy change (Delta H) of the reaction",
            "Biological catalysts are called enzymes"
        ],
        narration_script="Finally, let's explore catalysts! They act as molecular guides, carving a low-energy tunnel right through the mountain.",
        estimated_minutes=4
    )
    db.add(sec3)
    db.flush()

    q3 = Question(
        lesson_id=lesson.id,
        section_id=sec3.id,
        question_type="mcq",
        question_text="What is the primary mechanism by which a catalyst increases the rate of a chemical reaction?",
        options=[
            {"id": "A", "text": "It raises the temperature of the vessel"},
            {"id": "B", "text": "It provides an alternative reaction pathway with a lower activation energy (Ea)"},
            {"id": "C", "text": "It is permanently consumed in the reaction"},
            {"id": "D", "text": "It alters the equilibrium constant"}
        ],
        correct_answer="B",
        explanation="A catalyst provides an alternate pathway with a lower activation energy, dramatically increasing the rate without being consumed in the process.",
        difficulty="medium",
        concept_tested="Catalyst Mechanism"
    )
    db.add(q3)

    db.commit()
    db.refresh(lesson)
    return lesson

def seed_biology(db: Session, user_id: int) -> Lesson:
    existing = db.query(Lesson).filter(Lesson.user_id == user_id, Lesson.title.like("%DNA%")).first()
    if existing:
        db.delete(existing)
        db.commit()

    lesson = Lesson(
        user_id=user_id,
        title="Molecular Biology: DNA Structure, Replication & Central Dogma",
        subject="Biology",
        learning_objective="Explore the double helix architecture, complementary base pairing (A-T, G-C), semi-conservative replication, and protein synthesis.",
        target_level="Beginner",
        duration_minutes=16,
        language="English",
        teaching_style="Friendly Mentor",
        total_sections=3,
        current_section_index=0,
        current_mastery=25.0,
        status="in_progress"
    )
    db.add(lesson)
    db.flush()

    sec1 = LessonSection(
        lesson_id=lesson.id,
        section_index=0,
        title="The Double Helix Architecture & Base Pairing",
        concept="Complementary Hydrogen Bonds: A=T and G=C",
        explanation_text="DNA is a double-stranded helical molecule constructed from repeating nucleotides. Each nucleotide has a phosphate group, a deoxyribose sugar, and a nitrogenous base. Under Chargaff's rules, Adenine (A) always pairs with Thymine (T) via 2 hydrogen bonds, and Guanine (G) pairs with Cytosine (C) via 3 hydrogen bonds.",
        example_text="If one strand has the sequence 5'-A-G-T-C-3', its complementary strand must be 3'-T-C-A-G-5'.",
        analogy_text="A spiral staircase where the banisters are sugar-phosphate backbones and the paired steps are complementary nitrogenous bases.",
        visual_type="dna_helix",
        visual_data={"base_pairs": [["A", "T"], ["G", "C"], ["T", "A"], ["C", "G"]]},
        visual_caption="The DNA Double Helix Base Pairing Ladder",
        key_points=[
            "DNA strands run anti-parallel (5' to 3' opposite to 3' to 5')",
            "Adenine pairs with Thymine (2 H-bonds); Guanine pairs with Cytosine (3 H-bonds)",
            "The sugar-phosphate backbone provides structural stability on the exterior"
        ],
        narration_script="Welcome to Molecular Biology! Today we discover the code of life itself: the exquisite architecture of DNA.",
        estimated_minutes=4
    )
    db.add(sec1)
    db.flush()

    q1 = Question(
        lesson_id=lesson.id,
        section_id=sec1.id,
        question_type="mcq",
        question_text="According to Chargaff's rules, which nitrogenous base pairs with Guanine (G) in a DNA double helix, and with how many hydrogen bonds?",
        options=[
            {"id": "A", "text": "Adenine with 2 hydrogen bonds"},
            {"id": "B", "text": "Cytosine with 3 hydrogen bonds"},
            {"id": "C", "text": "Thymine with 1 hydrogen bond"},
            {"id": "D", "text": "Uracil with 4 hydrogen bonds"}
        ],
        correct_answer="B",
        explanation="Guanine (G) pairs exclusively with Cytosine (C) through three hydrogen bonds, while Adenine (A) pairs with Thymine (T) through two.",
        difficulty="easy",
        concept_tested="Chargaff's Base Pairing"
    )
    db.add(q1)

    sec2 = LessonSection(
        lesson_id=lesson.id,
        section_index=1,
        title="Semi-Conservative Replication Machinery",
        concept="Helicase, DNA Polymerase & The Replication Fork",
        explanation_text="Before a cell divides, it must duplicate its DNA. Helicase unzips the parental double helix. DNA Polymerase reads each exposed template strand and synthesizes a new complementary daughter strand in the 5' to 3' direction. Because each new DNA molecule retains one original template strand, replication is semi-conservative!",
        example_text="A cell with 46 chromosomes produces two identical daughter cells, each containing DNA composed of 50% original parental strand and 50% newly synthesized strand.",
        analogy_text="Unzipping a jacket: each half zipper teeth sequence can be used as a master template to machine a brand-new matching zipper half.",
        visual_type="mermaid",
        visual_data={"diagram": "graph TD\n  Parental[Parental Double Helix] --> Helicase[Helicase Unzips Strands]\n  Helicase --> Fork[Replication Fork]\n  Fork --> Leading[DNA Polymerase: Leading Strand 5'->3']\n  Fork --> Lagging[DNA Polymerase: Lagging Strand Okazaki Fragments]\n  Leading --> Daughter1[Daughter Molecule 1]\n  Lagging --> Daughter2[Daughter Molecule 2]"},
        visual_caption="Semi-Conservative DNA Replication at the Fork",
        key_points=[
            "Helicase unwinds the double helix by breaking hydrogen bonds",
            "DNA Polymerase synthesizes new DNA only in the 5' to 3' direction",
            "Semi-conservative means each new duplex contains one old and one new strand"
        ],
        narration_script="Now watch the molecular machines at work: Helicase unzips the helix, and DNA Polymerase precisely builds the matching daughter strands.",
        estimated_minutes=5
    )
    db.add(sec2)
    db.flush()

    q2 = Question(
        lesson_id=lesson.id,
        section_id=sec2.id,
        question_type="mcq",
        question_text="What is the primary function of the enzyme Helicase during DNA replication?",
        options=[
            {"id": "A", "text": "It glues DNA fragments together"},
            {"id": "B", "text": "It unwinds and separates the two strands of the DNA double helix by breaking hydrogen bonds"},
            {"id": "C", "text": "It translates RNA into protein"},
            {"id": "D", "text": "It destroys faulty cells"}
        ],
        correct_answer="B",
        explanation="Helicase moves along the DNA molecule, breaking the hydrogen bonds between base pairs to unwind and separate the two strands.",
        difficulty="medium",
        concept_tested="Helicase Function"
    )
    db.add(q2)

    sec3 = LessonSection(
        lesson_id=lesson.id,
        section_index=2,
        title="The Central Dogma: DNA -> RNA -> Protein",
        concept="Transcription and Translation",
        explanation_text="DNA holds the instructions, but proteins do the actual work in the cell. The Central Dogma describes the two-step flow of genetic information: 1) Transcription: RNA Polymerase transcribes a DNA gene into messenger RNA (mRNA). 2) Translation: The Ribosome reads the mRNA codons in triplets and synthesizes a corresponding chain of amino acids (protein).",
        example_text="The DNA triplet TAC codes for AUG on mRNA, which instructs the ribosome to insert Methionine, the universal start amino acid.",
        analogy_text="An architect's precious master blueprint kept safe in the office vault (DNA in nucleus), photocopied into a portable job-site recipe (mRNA), which construction workers (Ribosomes) use to build the actual building (Protein).",
        visual_type="katex",
        visual_data={"formula": "\\text{DNA (Replication)} \\xrightarrow{\\text{Transcription}} \\text{mRNA} \\xrightarrow{\\text{Translation}} \\text{Functional Protein}"},
        visual_caption="The Central Dogma of Molecular Biology",
        key_points=[
            "Transcription occurs in the nucleus, producing an mRNA transcript",
            "Translation occurs at ribosomes in the cytoplasm, assembling amino acids",
            "Codons are 3-nucleotide sequences that specify a single amino acid"
        ],
        narration_script="Finally, we explore the Central Dogma: how the static genetic code transforms into dynamic, living proteins that power our bodies.",
        estimated_minutes=4
    )
    db.add(sec3)
    db.flush()

    q3 = Question(
        lesson_id=lesson.id,
        section_id=sec3.id,
        question_type="mcq",
        question_text="In the Central Dogma of Molecular Biology, what is the correct sequence of information flow?",
        options=[
            {"id": "A", "text": "Protein -> RNA -> DNA"},
            {"id": "B", "text": "DNA -> mRNA (Transcription) -> Protein (Translation)"},
            {"id": "C", "text": "mRNA -> DNA -> Amino Acids"},
            {"id": "D", "text": "Protein -> DNA -> RNA"}
        ],
        correct_answer="B",
        explanation="Information flows from DNA to messenger RNA via transcription, and from mRNA to functional protein via translation.",
        difficulty="easy",
        concept_tested="Central Dogma"
    )
    db.add(q3)

    db.commit()
    db.refresh(lesson)
    return lesson

def seed_all_courses_for_user(db: Session, user_id: int) -> List[Lesson]:
    lessons = [
        seed_ohms_law(db, user_id),
        seed_neural_networks(db, user_id),
        seed_calculus(db, user_id),
        seed_chemistry(db, user_id),
        seed_biology(db, user_id)
    ]
    return lessons

@router.get("/courses")
def get_courses_catalog():
    """
    Returns the complete catalog of all 5 ready-to-teach foundational courses.
    """
    return COURSES_CATALOG

@router.post("/reset-ohms-law", response_model=LessonResponse)
def seed_ohms_law_demo(db: Session = Depends(get_db)):
    """
    Initializes or resets the signature Ohm's Law demonstration lesson.
    """
    demo_user = ensure_demo_user(db)
    lesson = seed_ohms_law(db, demo_user.id)
    return LessonResponse.model_validate(lesson)

@router.post("/seed-all-courses", response_model=List[LessonResponse])
def seed_all_courses_endpoint(db: Session = Depends(get_db)):
    """
    Initializes and seeds all 5 complete course curricula into the database.
    """
    demo_user = ensure_demo_user(db)
    lessons = seed_all_courses_for_user(db, demo_user.id)
    return [LessonResponse.model_validate(l) for l in lessons]

@router.post("/select-course/{slug}", response_model=LessonResponse)
def select_course_endpoint(slug: str, db: Session = Depends(get_db)):
    """
    Selects or resets a specific course by slug (ohms-law, neural-networks, calculus-derivatives, chemical-bonding, dna-genetics).
    """
    demo_user = ensure_demo_user(db)
    slug_clean = slug.lower().strip()
    
    if "ohm" in slug_clean or "circuit" in slug_clean:
        lesson = seed_ohms_law(db, demo_user.id)
    elif "neural" in slug_clean or "ai" in slug_clean or "deep" in slug_clean:
        lesson = seed_neural_networks(db, demo_user.id)
    elif "calculus" in slug_clean or "deriv" in slug_clean or "math" in slug_clean:
        lesson = seed_calculus(db, demo_user.id)
    elif "chem" in slug_clean or "bond" in slug_clean:
        lesson = seed_chemistry(db, demo_user.id)
    elif "bio" in slug_clean or "dna" in slug_clean or "genet" in slug_clean:
        lesson = seed_biology(db, demo_user.id)
    else:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Course with slug '{slug}' not found in catalog."
        )
    
    return LessonResponse.model_validate(lesson)
